apiVersion: batch/v1
kind: Job
metadata:
  name: minio-mkbucket
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              until mc alias set local http://minio:9000 chat chatchat123; do
                echo "waiting for minio..."; sleep 2;
              done
              mc mb --ignore-existing local/media
